export const CHANGE_DIFFICULTY = 'CHANGE_DIFFICULTY';
export const ADD_COLOR_TO_SEQUENCE = 'ADD_COLOR_TO_SEQUENCE';
export const SET_ACTIVE_COLOR = 'SET_ACTIVE_COLOR';
export const CHANGE_PLAYING_STATUS = 'CHANGE_PLAYING_STATUS';
export const WRITE_INPUT_INDEX = 'WRITE_INPUT_INDEX';
export const FAIL_GAME = 'FAIL_GAME';
export const TURN_GAME_OFF = 'TURN_GAME_OFF';
